config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: { sessions: 'owners/sessions' }

  resources :stores do
    resources :goals, except: [ :index, :show ]
  end

  root 'home#index'
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :owner
  has_many :sellers, dependent: :destroy
  has_many :goals, dependent: :destroy

  attr_list :owner, :name

  accepts_nested_attributes_for :sellers, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :sellers, presence: { if: 'true', message: I18n.t('errors.messages.empty') }

  orderize 'id DESC'
end

app/controllers/stores_controller.rb
class StoresController < CrudController
  before_action :set_store, only: [ :show, :edit, :update, :destroy ]

  # GET /stores
  def index
    @stores = current_owner.stores.ordered
  end

  # GET /stores/1
  def show
  end

  # GET /stores/new
  def new
    @store = current_owner.stores.build
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  def create
    @store = current_owner.stores.build(store_params)

    if @store.save
      respond_with(@store)
    else
      render :new
    end
  end

  # PATCH/PUT /stores/1
  def update
    if @store.update(store_params)
      respond_with(@store)
    else
      render :edit
    end
  end

  # DELETE /stores/1
  def destroy
    @store.destroy
    respond_with(@store)
  end

  private

  def set_store
    @store = current_owner.stores.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, sellers_attributes: [ :id, :name, :_destroy])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
  include CrudHelper

  def resource_class
    Store
  end

  def resource
    @store
  end

  def collection
    @stores
  end

  def new_path
    new_store_path
  end

  def edit_path(resource)
    edit_store_path(resource)
  end

  def index_path
    stores_path
  end
end

app/views/stores/_form.html.haml
= f.input :name

%h3= plural(Seller)

#sellers
  = render 'crud/form_errors', errors: f.object.errors[:sellers]

  = f.simple_fields_for :sellers do |seller|
    = render 'sellers/fields', f: seller

  .links
    = link_to_add_association t('buttons.add', resource: singular(Seller)), f, :sellers, partial: 'sellers/fields', class: 'btn btn-info btn-flat'

app/views/stores/show.html.haml
.row
  .col-md-12
    .box
      .box-header.with-border
        %h3.box-title= singular(resource_class)
      .box-body
        .nav-tabs-custom
          %ul.nav.nav-tabs
            %li.active
              %a{ 'aria-expanded':  'true', 'data-toggle':  'tab', href:  '#tab_1' }= t('title.general_data')
            %li
              %a{ 'aria-expanded':  'false', 'data-toggle':  'tab', href:  '#tab_2' }= plural(Seller)
            %li
              %a{ 'aria-expanded':  'false', 'data-toggle':  'tab', href:  '#tab_3' }= plural(Goal)

          .tab-content
            #tab_1.tab-pane.active
              %dl
                - show_attributes.each do |attribute|
                  %dt= localized_attribute(resource_class, attribute)
                  %dd= formatted_attribute(resource, attribute)

            #tab_2.tab-pane
              = render 'sellers/list'

            #tab_3.tab-pane
              = new_link(new_store_goal_path(resource))

              %hr

              = render 'goals/list'

      .box-footer
        = edit_button(edit_path(resource))
        = back_button