config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: { sessions: 'owners/sessions' }

  resources :stores do
    resources :goals, except: [ :index, :show ]
  end

  root 'home#index'
end

app/models/goal.rb
class Goal < ApplicationRecord
  attr_accessor :date

  belongs_to :store
  has_many :goal_days, dependent: :destroy
  has_many :goal_day_sellers, through: :goal_days

  attr_list :start_date, :end_date, :value

  accepts_nested_attributes_for :goal_days, reject_if: :all_blank, allow_destroy: true

  validates_associated :goal_days

  validates :date, :start_date, :end_date, :value, presence: true
  validates :goal_days, presence: { if: 'true', message: I18n.t('errors.messages.empty') }

  validates_numericality_of :value, greater_than: 0.0

  validate :check_goal_days_size
  validate :check_if_dates_between_other_goals
  validate :check_if_goal_days_values_is_equal_value

  orderize 'start_date ASC'

  private

  # Verifica o número de dias entre a data de início e término e verifica se esses dias
  # foram inseridos nos dias da meta. Senão, informa o erro com a data para ser inserida
  def check_goal_days_size
    return false unless start_date
    return false unless end_date

    _start_date = start_date

    while _start_date <= end_date
      unless goal_days.reject(&:marked_for_destruction?).select { |s| s.date == _start_date }.any?
        errors.add(
          :goal_days,
          I18n.t(
            'activerecord.errors.goal.not_have_goal_day_with_date_not_informed',
            day: I18n.l(_start_date)
          )
        )
      end

      _start_date += 1.day
    end
  end

  # Verifica se as datas entre início e término constam em outra meta da mesma loja.
  # Se sim, informa o erro com datas já escolhidas em outra meta
  def check_if_dates_between_other_goals
    if store && Goal.where(
      'store_id = ? AND id <> ? AND ((start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?))',
      store.id, id.to_i, start_date, end_date, start_date, end_date
    ).any?
      errors.add(:date, I18n.t('activerecord.errors.goal.chosen_date_is_already_in_another_goal'))
    end
  end

  # Verifica se os valores dos dias da meta é igual ao valor da meta. Senão, informa o erro com
  # a soma dos valores dos dias da meta diferente do valor da meta
  def check_if_goal_days_values_is_equal_value
    if goal_days.any? && goal_days.reject(&:marked_for_destruction?).select{ |s| s.value.present? }.sum(&:value) != value
      errors.add(:goal_days, I18n.t('activerecord.errors.goal.sum_goal_days_values_is_different_of_value'))
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < CrudController
  before_action :set_store, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :set_goal, only: [ :edit, :update, :destroy ]

  # GET /stores/:store_id/goals/new
  def new
    @goal = @store.goals.build
  end

  # GET /stores/:store_id/goals/:id/edit
  def edit
  end

  # POST /stores/:store_id/goals
  def create
    @goal = @store.goals.build(goal_params)

    if @goal.save
      respond_with(@goal) do |format|
        format.html { redirect_to store_path(@store) }
      end
    else
      render :new
    end
  end

  # PATCH/PUT /stores/:store_id/goals/:id
  def update
    if @goal.update(goal_params)
      respond_with(@goal) do |format|
        format.html { redirect_to store_path(@store) }
      end
    else
      render :edit
    end
  end

  # DELETE /stores/:store_id/goals/:id
  def destroy
    @goal.destroy
    respond_with(@goal) do |format|
      format.html { redirect_to store_path(@store) }
    end
  end

  private

  def set_store
    @store = Store.find_by!(id: params[:store_id], owner_id: current_owner.id)
  end

  def set_goal
    @goal = @store.goals.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:store_id, :date, :start_date, :end_date, :value,
                                 goal_days_attributes: [
                                   :id, :date, :value, :_destroy,
                                   goal_day_sellers_attributes: [
                                     :id, :seller_id, :_destroy
                                   ]
                                 ])
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
  include CrudHelper

  def resource_class
    Goal
  end

  def resource
    @goal
  end

  def index_path
    store_path(@store)
  end
end

app/views/goals/_form.html.haml
= f.input :date, as: :string, required: true
= f.input :start_date, as: :hidden, input_html: { value: (l(f.object.start_date) if f.object.start_date) }
= f.input :end_date, as: :hidden, input_html: { value: (l(f.object.end_date) if f.object.end_date) }
= f.input :value

%h3= plural(GoalDay)

#goal-days
  = render 'crud/form_errors', errors: f.object.errors[:goal_days]

  = f.simple_fields_for :goal_days do |goal_day|
    = render 'goal_days/fields', f: goal_day

  .links
    = link_to_add_association t('buttons.add', resource: singular(GoalDay)),
      f, :goal_days, partial: 'goal_days/fields', class: 'btn btn-info btn-flat add_goal_days'

app/views/goals/_list.html.haml
.dataTables_wrapper.table-scrollable.form-inline.no-footer
  %table.table.table-striped.table-bordered.table-hover.dataTable{ width: '100%' }
    %thead
      = render 'goals/list_header'
    %tbody
      = render 'goals/list_body'

app/views/goals/_list_actions.html.haml
%td{ width: '10%' }
  .btn-group
    %button.btn.btn-default.dropdown-toggle{ 'aria-expanded': 'false', 'data-toggle': 'dropdown', type: 'button' }
      = t('actions.actions')

      %span.caret
      %span.sr-only
    %ul.dropdown-menu{ role: 'menu' }
      %li
        = edit_link(edit_store_goal_path(resource, object))
      %li
        = destroy_link(store_goal_path(resource, object))

app/views/goals/_list_body.html.haml
- resource.goals.ordered.each do |object|
  %tr{ id: "#{dom_id(object)}", class: 'active' }
    - list_attributes(Goal).each do |attribute|
      %td= formatted_attribute(object, attribute)

    = render 'goals/list_actions', object: object

  %tr
    %td{ colspan: '4' }
      %div{ style: 'padding-left: 10px' }
        - object.goal_days.ordered.each_with_index do |goal_day, index|
          %h6= l goal_day.date

          - goal_day.goal_day_sellers.each do |goal_day_seller|
            .row
              .col-md-1
                %dd= formatted_attribute(goal_day_seller, :seller)

              .col-md-1
                %dd= formatted_attribute(goal_day, :sellers_value)

          - if object.goal_days[index.next]
            %hr

app/views/goals/_list_header.html.haml
%tr
  - list_attributes(Goal).each do |attribute|
    %th= localized_attribute(Goal, attribute)

  %th{ width: '50px' }

app/views/goals/edit.html.haml
.row
  .col-md-12
    .box
      .box-header.with-border
        %h3.box-title= t('title.edit', resource: singular(resource_class))

      = simple_form_for resource, url: store_goal_path(@store, resource), method: :put do |f|
        .box-body
          = render 'crud/form_errors', errors: f.object.errors[:base]
          = render 'form', f: f
        .box-footer
          = f.submit t('buttons.save'), class: 'btn btn-primary btn-flat'

          = back_button

app/views/goals/new.html.haml
.row
  .col-md-12
    .box
      .box-header.with-border
        %h3.box-title= t('title.create', resource: singular(resource_class))

      = simple_form_for resource, url: store_goals_path, method: :post do |f|
        .box-body
          = render 'crud/form_errors', errors: f.object.errors[:base]
          = render 'form', f: f
        .box-footer
          = f.submit t('buttons.save'), class: 'btn btn-primary btn-flat'

          = back_button