config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: { sessions: 'owners/sessions' }

  resources :stores do
    resources :goals, except: [ :index, :show ]
  end

  root 'home#index'
end

app/views/layouts/_flash_message.html.haml
- if notice
  .alert.alert-success.alert-dismissable
    %i.fa.fa-check
    %button.close{ "aria-hidden": "true", "data-dismiss": "alert", type: "button" } ×
    %b= notice
- elsif alert
  .alert.alert-danger.alert-dismissable
    %i.fa.fa-ban
    %button.close{"aria-hidden": "true", "data-dismiss": "alert", type: "button" } ×
    %b= alert

app/views/layouts/_header.html.haml
%header.main-header
  %a.logo{ href: "/" }
    %span.logo-mini
      %b> i
    %span.logo-lg
      %b> Indeva
  %nav.navbar.navbar-static-top{ role: 'navigation' }
    %a.sidebar-toggle{ 'data-toggle': 'offcanvas', href: "#", role: 'button' }
      %span.sr-only
    .navbar-custom-menu
      %ul.nav.navbar-nav
        %li.dropdown.user.user-menu
          %a.dropdown-toggle{ 'data-toggle': 'dropdown', href: '#' }
            %span.hidden-xs= current_owner.email
          %ul.dropdown-menu
            %li= link_to t('actions.signout'), destroy_owner_session_path, method: :delete, class: 'btn btn-danger btn-flat'

app/views/layouts/_menu.html.haml
%ul.sidebar-menu
  %li#menu-home
    = link_to root_path do
      %i.fa.fa-home
      %span Home
  %li#menu-stores
    = link_to stores_path do
      %i.fa.fa-building
      %span= plural(Store)

app/views/layouts/_sidebar.html.haml
%aside.main-sidebar
  %section.sidebar
    .user-panel{ style: 'width: auto; height: 60px;' }
      .pull-left.info{ style: 'left: 0;' }
        %p= current_owner.email
        = link_to t('actions.signout'), destroy_owner_session_path, method: :delete
    = render 'layouts/menu'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content:' "text/html; charset=UTF-8"', "http-equiv": 'Content-Type' }
    %meta{ charset: "UTF-8" }
    %title Indeva
    %meta{ content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', name: 'viewport' }
    %link{ href: 'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css', rel: 'stylesheet', type: 'text/css' }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'jquery'
    <!--[if lt IE 9]>
    %script{ src: 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' }
    %script{ src: 'https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js' }
    <![endif]-->
  = csrf_meta_tags
  %body{ class: 'skin-blue sidebar-mini', 'data-menu': params[:controller].parameterize }
    .wrapper
      = render partial: 'layouts/header'
      = render partial: 'layouts/sidebar'
      .content-wrapper
        %section.content-header
          = render 'layouts/flash_message'
        %section.content
          = yield
    = javascript_include_tag 'application'

app/views/layouts/login.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %title Log in
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/

    = stylesheet_link_tag 'application', media: 'all'

    <!--[if lt IE 9]>
    %script{ src: 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' }
    %script{ src: 'https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js' }
    <![endif]-->

  = csrf_meta_tags

  = javascript_include_tag 'jquery'

  %body.login-page
    .login-box
      .login-box-body
        %p.login-box-msg Indeva
        = render 'layouts/flash_message'

        = simple_form_for resource, url: session_path(resource_name) do |f|
          .form-group.has-feedback
            = f.input :email, as: :email, label: false, autofocus: true, input_html: { class: 'form-control' }
            %span.glyphicon.glyphicon-envelope.form-control-feedback
          .form-group.has-feedback
            = f.input :password, as: :password, label: false, autocomplete: 'off', input_html: { class: 'form-control' }
            %span.glyphicon.glyphicon-lock.form-control-feedback
          .row
            .col-xs-4
              = f.submit t('actions.signin'), class: 'btn btn-primary btn-block btn-flat'

    = javascript_include_tag 'application'